### ISSUE TITLE
[Bug] Scrolling up moves everything down, including the footer bar

### ISSUE THREAD

**Issue by RaptaG** [mineblock11/android-modrinth-dashboard#12]
![](https://github.com/mineblock11/android-modrinth-dashboard/assets/77157639/52c6665a-ab02-4aea-9c23-1b31a5e9d35d)

**Comment by RaptaG** [comment]
It should only move down the content, not the bar

**Comment by mineblock11** [comment]
Im not sure I understand this, do you have a video recording of this happening?

**Comment by RaptaG** [comment]
https://github.com/mineblock11/android-modrinth-dashboard/assets/77157639/9a199ef9-60bf-4eb5-b62f-3326a6467d2b


Look down!

**Comment by mineblock11** [comment]
That's just native android animations, this happens on all apps when you over scroll - the animation is there to emphasise that you can't scroll any further.
